version: "1"
services:
  frontend:
    image: todo_web_frontend
    environment:
      BACKEND: localhost:1880
    ports:
      - "80:8080"
  backend:
    image: todo_web_backend
    environment:
      SECRET: ${SECRET}
    ports:
      - "1880:1880"
